version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: host.docker.internal  # Connect to the host machine's MySQL
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: employee_details
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
